In [6]:
from pyspark import SparkConf
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql import functions as F
import boto3
import sys
import re
from datetime import datetime
import configparser
from pyspark.sql.functions import *

VBox()

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

In [5]:
%%configure -f
{
    "conf": {
        "spark.jars": "s3://sjet-datamart-bucket/Jars/mssql-jdbc-6.1.0.jre8.jar",
        "spark.sql.crossJoin.enabled": "true"
    }
}

Starting Spark application

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

SparkSession available as 'spark'.

In [13]:
Q400_128WPS_1 = spark.sql('''
                        SELECT
                        
                        ECN,
                        
                        UTC_TIMEDATE,
                        
                        FileName,

                        CAST((MAX(`Time-In-Secs`) - MIN(`Time-In-Secs`)) / 60 AS INT) AS FlightTime
             
                        FROM precogdb.q400128wps
                        
                        WHERE FlightDate > '2022-10-31'
                        
                        AND `Radio-Altitude` NOT LIKE '%*%'
                        
                        AND `Radio-Altitude` <> ''
                        
                        AND `Main-WOW` = 'Air (0)'

                        AND  CAST(LoadedDate AS DATE) = CAST (current_timestamp AS DATE)

                        GROUP BY ECN, UTC_TIMEDATE, Filename
                            ''')

Q400_128WPS_1.createOrReplaceTempView('Q400_128WPS_1')

Q400_Time = spark.sql('''

                                SELECT CAST((MAX(CAST(`Time-in-secs` AS INT)) - MIN(CAST(`Time-in-secs` AS INT))) / 60 AS INT) AS BlockTime_DFDR, filename
                                
                                FROM precogdb.q400128wps
                                
                                WHERE FlightDate > '2022-10-31'

                                AND  CAST(LoadedDate AS DATE) = CAST (current_timestamp AS DATE)
                                
                                group by filename
                            ''')

Q400_Time.createOrReplaceTempView('Q400_Time')

Q400_128WPS_2 = spark.sql('''

                        SELECT 
                        
                            DISTINCT
                        
                               Cast(ChocksOff as Date) AS FlightDate,
                               
                               TailNo,
                               
                               Departure,
                               
                               ChocksOff,
                               
                               date_format(ChocksOff, 'HH:mm:ss') AS Actual_DEP_Time,
                               
                               Arrival,
                               
                               date_format(ChocksOn, 'HH:mm:ss') AS Actual_ARR_Time,
                               
                               (bigint(to_timestamp(ChocksOn)) - bigint(to_timestamp(ChocksOff))) / 60 AS BlockTime_ARMS, 
                               
                               CONCAT(Departure, '-', Arrival) AS Sector,
                                                    
                               desigflightnumber AS FlightNo,
                               
                               Date,
                               
                               ECN,
                               
                               UTC_TIMEDATE,
                               
                               CAST(SUM((CAST (`fuel-flow-no-2-kg` AS INT) + CAST (`fuel-flow-no-1-kg` AS INT))) OVER (PARTITION BY ECN, UTC_TIMEDATE, Filename) / 3600 AS INT) AS FuelConsumed,
                               
                               FileName,
                               
                               loadeddate,
                               
                               year,
                               
                               month
                               
                              FROM precogdb.q400128wps
                        
                        WHERE FlightDate > '2022-10-31'
                        
                        AND CAST(LoadedDate AS DATE) = CAST (current_timestamp AS DATE)
                        
                        AND `Radio-Altitude` NOT LIKE '%*%'
                        
                        AND `Radio-Altitude` <> ''
                        
                        AND UTC_TIMEDATE BETWEEN (ChocksOff - INTERVAL 360 MINUTES) AND (ChocksOff - INTERVAL 300 MINUTES)
             
                        ''')

Q400_128WPS_2.createOrReplaceTempView('Q400_128WPS_2')

Q400_128WPS_2_1 = spark.sql('''

                        SELECT a.*,b.Blocktime_DFDR
                        
                        FROM Q400_128WPS_2 a 
                        
                        left JOIN Q400_Time b
                        
                        ON a.filename = b.filename
                    ''')

Q400_128WPS_2_1.createOrReplaceTempView('Q400_128WPS_2_1')

Q400_128WPS_3 = spark.sql('''

                SELECT MIN(`Time-Per-Sec`) AS AirborneTime,
                
                ECN,
                        
                UTC_TIMEDATE,
                
                flightdate,
                
                Filename
                
                FROM precogdb.q400128wps
                
                WHERE FlightDate > '2022-10-31'
                        
                AND `Radio-Altitude` NOT LIKE '%*%'
                        
                AND `Radio-Altitude` <> ''
                        
                AND `Main-WOW` = 'Air (0)'

                AND CAST(LoadedDate AS DATE) = CAST (current_timestamp AS DATE)

                GROUP BY ECN,
                        
                        UTC_TIMEDATE,flightdate,Filename
            ''')

Q400_128WPS_3.createOrReplaceTempView('Q400_128WPS_3')

Q400_128WPS_3_1 = spark.sql('''SELECT MIN(`Time-Per-Sec`) AS TouchDownTime,
                    
                    flightdate,
                    
                    ECN,
                            
                    UTC_TIMEDATE,
                    
                    Filename
                    
                    FROM precogdb.q400128wps
                    
                    WHERE FlightDate > '2022-10-31'
                            
                    AND `Radio-Altitude` NOT LIKE '%*%'
                            
                    AND `Radio-Altitude` <> ''
                    
                    AND `Main-WOW` = 'Gnd (1)'
                    
                    AND `time-per-sec` NOT LIKE '%*%'
                    
                    AND `time-in-secs` > 2500
                            
                    AND CAST(LoadedDate AS DATE) = CAST (current_timestamp AS DATE)

                    GROUP BY ECN,
                            
                            UTC_TIMEDATE,flightdate,Filename ''')

Q400_128WPS_3_1.createOrReplaceTempView('Q400_128WPS_3_1')

Q400_128WPS_3_2 = spark.sql('''

                SELECT a.ECN, a.UTC_TIMEDATE, a.AirborneTime, b.TouchDownTime, a.Filename, a.Flightdate
                
                FROM Q400_128WPS_3 a 
                
                JOIN Q400_128WPS_3_1 b on a.Filename = b.Filename
                
                AND a.Flightdate = b.Flightdate
    ''')

Q400_128WPS_3_2.createOrReplaceTempView('Q400_128WPS_3_2')

Q400_128WPS_4 = spark.sql('''

                                SELECT ECN, UTC_TIMEDATE, filename, flightdate,
                                
                                CASE 
                                    WHEN LENGTH(CAST(`AirborneTime` as String)) = 1 THEN CONCAT('00000',CAST(`AirborneTime` as String)) 
                                    WHEN LENGTH(CAST(`AirborneTime` as String)) = 2 THEN CONCAT('0000',CAST(`AirborneTime` as String)) 
                                    WHEN LENGTH(CAST(`AirborneTime` as String)) = 3 THEN CONCAT('000',CAST(`AirborneTime` as String))
                                    WHEN LENGTH(CAST(`AirborneTime` as String)) = 4 THEN CONCAT('00',CAST(`AirborneTime` as String)) 
                                    WHEN LENGTH(CAST(`AirborneTime` as String)) = 5 THEN CONCAT('0',CAST(`AirborneTime` as String))
                                    ELSE `AirborneTime`
                                END As AirborneTime,
                                CASE 
                                    WHEN LENGTH(CAST(`TouchdownTime` as String)) = 1 THEN CONCAT('00000',CAST(`TouchdownTime` as String)) 
                                    WHEN LENGTH(CAST(`TouchdownTime` as String)) = 2 THEN CONCAT('0000',CAST(`TouchdownTime` as String)) 
                                    WHEN LENGTH(CAST(`TouchdownTime` as String)) = 3 THEN CONCAT('000',CAST(`TouchdownTime` as String))
                                    WHEN LENGTH(CAST(`TouchdownTime` as String)) = 4 THEN CONCAT('00',CAST(`TouchdownTime` as String)) 
                                    WHEN LENGTH(CAST(`TouchdownTime` as String)) = 5 THEN CONCAT('0',CAST(`TouchdownTime` as String))
                                    ELSE `TouchdownTime`
                                END As TouchdownTime
                                
                                                                    
                                FROM Q400_128WPS_3_2
                                                    
                        ''')

Q400_128WPS_4.createOrReplaceTempView('Q400_128WPS_4')

Q400_128WPS_5 = Q400_128WPS_4.withColumn("AirborneTime", regexp_replace(col("AirborneTime") , "(\\d{2})(\\d{2})(\\d{2})" , "$1:$2:$3" )) \
                                .withColumn("TouchdownTime", regexp_replace(col("TouchdownTime") , "(\\d{2})(\\d{2})(\\d{2})" , "$1:$2:$3" ))

Q400_128WPS_5.createOrReplaceTempView('Q400_128WPS_5')

Q400_128WPS_6 = spark.sql('''

                    SELECT to_timestamp(concat(flightdate,' ',AirborneTime)) AS Airborne_Time,
                    
                    to_timestamp(concat(flightdate,' ',TouchdownTime)) AS Touchdown_Time,
                    
                    Filename,
                    
                    ECN, 
                    
                    UTC_TIMEDATE
                    
                    FROM Q400_128WPS_5


    ''')

Q400_128WPS_6.createOrReplaceTempView('Q400_128WPS_6')

Q400_128WPS_7 = spark.sql('''

                    SELECT (Airborne_Time + INTERVAL 330 MINUTES) AS AirborneTime, 
                    
                    (Touchdown_Time + INTERVAL 330 MINUTES) AS TouchdownTime,
                    
                    Filename,
                    
                    ECN, UTC_TIMEDATE
                    
                    FROM Q400_128WPS_6
                    
                    ''')

Q400_128WPS_8 = Q400_128WPS_7.withColumn('Airborne_Time', date_format('AirborneTime', 'HH:mm:ss')) \
                                .withColumn('Touchdown_Time', date_format('TouchdownTime', 'HH:mm:ss'))

Q400_128WPS_8.createOrReplaceTempView('Q400_128WPS_8')

Q400_FOB_1 = spark.sql('''

                        SELECT 
                        
                        b.flightdate,
                                
                                b.TailNo,
                                
                                b.Departure,
                                
                                b.Actual_DEP_Time,
                                
                                c.Airborne_Time,
                                
                                c.Touchdown_Time,
                                
                                b.Arrival,
                                
                                b.Sector,
                                
                                b.Actual_ARR_Time,
                                
                                b.Blocktime_ARMS,
                                
                                b.Blocktime_DFDR,
                                
                                a.FlightTime,
                                                        
                                b.FlightNo,
                                
                                b.Date,
                                
                                b.FuelConsumed,
                                
                                b.FileName,
                                
                                b.loadeddate,
                                
                                b.year,
                                
                                b.month
                                
                                FROM Q400_128WPS_1 a
                                
                                INNER JOIN Q400_128WPS_2_1 b
                                
                                INNER JOIN Q400_128WPS_8 c
                                
                                on a.filename = b.filename
                                
                                and a.ECN = b.ECN
                                
                                and a.UTC_TIMEDATE = b.UTC_TIMEDATE
                                
                                and a.filename = c.filename
                                
                                and a.ECN = c.ECN
                                
                                and a.UTC_TIMEDATE = c.UTC_TIMEDATE
                                
                            ''')

Q400_FOB_1.createOrReplaceTempView('Q400_FOB_1')

Q400_FOB = spark.sql('''

        SELECT 
                        
                        flightdate,
                                
                                TailNo,
                                
                                Departure,
                                
                                Actual_DEP_Time,
                                
                                Airborne_Time,
                                
                                Touchdown_Time,
                                
                                Arrival,
                                
                                Sector,
                                
                                Actual_ARR_Time,
                                
                                CONCAT( CASE 
                                        WHEN LENGTH ( CAST(CAST(Blocktime_ARMS / 60 AS INT) AS STRING)) =1
                                        THEN CONCAT('0',CAST(CAST(Blocktime_ARMS / 60 AS INT) AS STRING))
                                        ELSE CAST(CAST(Blocktime_ARMS / 60 AS INT) AS STRING)
                                    END,
                                    ':',
                                    CASE 
                                        WHEN LENGTH ( CAST(CAST(Blocktime_ARMS % 60 AS INT) AS STRING)) =1
                                        THEN CONCAT('0',CAST(CAST(Blocktime_ARMS % 60 AS INT) AS STRING))
                                        ELSE CAST(CAST(Blocktime_ARMS % 60 AS INT) AS STRING)
                                    END ) AS BlockTime_ARMS,
                                
                                    CONCAT( CASE 
                                        WHEN LENGTH ( CAST(CAST(Blocktime_DFDR / 60 AS INT) AS STRING)) =1
                                        THEN CONCAT('0',CAST(CAST(Blocktime_DFDR / 60 AS INT) AS STRING))
                                        ELSE CAST(CAST(Blocktime_DFDR / 60 AS INT) AS STRING)
                                    END,
                                    ':',
                                    CASE 
                                        WHEN LENGTH ( CAST(CAST(Blocktime_DFDR % 60 AS INT) AS STRING)) =1
                                        THEN CONCAT('0',CAST(CAST(Blocktime_DFDR % 60 AS INT) AS STRING))
                                        ELSE CAST(CAST(Blocktime_DFDR % 60 AS INT) AS STRING)
                                    END ) AS BlockTime_DFDR,
                                
                                    CONCAT( CASE 
                                        WHEN LENGTH ( CAST(CAST(FlightTime / 60 AS INT) AS STRING)) =1
                                        THEN CONCAT('0',CAST(CAST(FlightTime / 60 AS INT) AS STRING))
                                        ELSE CAST(CAST(FlightTime / 60 AS INT) AS STRING)
                                    END,
                                    ':',
                                    CASE 
                                        WHEN LENGTH ( CAST(CAST(FlightTime % 60 AS INT) AS STRING)) =1
                                        THEN CONCAT('0',CAST(CAST(FlightTime % 60 AS INT) AS STRING))
                                        ELSE CAST(CAST(FlightTime % 60 AS INT) AS STRING)
                                    END ) AS FlightTime,
                                                        
                                    FlightNo,
                                
                                    Date,
                                
                                    FuelConsumed,
                                
                                    FileName,
                                
                                    loadeddate,
                                
                                    year,
                                
                                    month

                                    FROM Q400_FOB_1
        

        
        
        ''')

Q400_FOB.createOrReplaceTempView('Q400_FOB')

SALTDF = spark.read \
  .format("jdbc") \
  .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
  .option("url", "jdbc:sqlserver://10.150.72.22:1433;databaseName=SALT") \
  .option("dbtable", "LoadAndTrimDetails") \
  .option("user", "dmbigdata") \
  .option("password", "$p!Ce@bigData$db") \
  .load()

SALTDF.createOrReplaceTempView('SALTDF')

Q400FinalFOBDF = spark.sql('''

                SELECT a.flightdate,
                               
                               a.TailNo,
                               
                               a.FlightNo,
                               
                               a.Sector,
                               
                               a.Departure,
                               
                               a.Actual_DEP_Time,
                               
                               a.Airborne_Time,
                               
                               a.Touchdown_Time,
                               
                               a.Arrival,
                               
                               a.Actual_ARR_Time,
                               
                               b.FOB,
                               
                               (CAST (b.FOB AS INT) + 105) AS DepartureFuel,
                               
                               a.FuelConsumed,
                               
                               a.BlockTime_ARMS,
                               
                               a.BlockTime_DFDR,
                               
                               a.FlightTime,
                                                    
                               ((CAST (b.FOB AS INT) + 105) - CAST (a.FuelConsumed AS INT)) AS ArrivalFuel,
                               
                               a.FileName,
                               
                               a.loadeddate,
                               
                               a.year,
                               
                               a.month,

                               current_timestamp()   AS `ProcessedDate`

                               FROM Q400_FOB a 
                
                                LEFT JOIN SALTDF b on a.FlightDate = CAST(b.FlightDate AS date)
                                
                                AND REPLACE(a.FlightNo,' ','') = b.FlightNo
                                
                                AND a.Departure = b.Source
                                
                                AND a.Arrival = b.Destination
                
                ''')

VBox()

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

In [15]:
Q400FinalFOBDF.show(truncate = False)

VBox()

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

+----------+------+--------+-------+---------+---------------+-------------+--------------+-------+---------------+----+-------------+------------+--------------+--------------+----------+-----------+------------------------------------------------------------+-----------------------+----+-------+-----------------------+
|flightdate|TailNo|FlightNo|Sector |Departure|Actual_DEP_Time|Airborne_Time|Touchdown_Time|Arrival|Actual_ARR_Time|FOB |DepartureFuel|FuelConsumed|BlockTime_ARMS|BlockTime_DFDR|FlightTime|ArrivalFuel|FileName                                                    |loadeddate             |year|month  |ProcessedDate          |
+----------+------+--------+-------+---------+---------------+-------------+--------------+-------+---------------+----+-------------+------------+--------------+--------------+----------+-----------+------------------------------------------------------------+-----------------------+----+-------+-----------------------+
|2023-01-16|VT-SUG|SG 3762 |AMD-JSA|AMD      |07:45:00       |08:07:06     |09:12:22      |JSA    |09:20:00       |null|null         |1233        |01:35         |01:26         |01:05     |null       |ALL ac=VT-SUG dep=AMD arr=JSA fn=SEJ3762 dt=20230116.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUQ|SG 2909 |BLR-GOI|BLR      |20:20:00       |20:43:46     |21:42:54      |GOI    |21:55:00       |2890|2995         |1122        |01:35         |01:18         |00:59     |1873       |ALL ac=VT-SUQ dep=BLR arr=GOI fn=SEJ2909 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-14|VT-SUG|SG 3426 |GOI-STV|GOI      |19:21:00       |19:31:16     |20:44:04      |STV    |20:51:00       |2795|2900         |1260        |01:30         |01:20         |01:12     |1640       |ALL ac=VT-SUG dep=GOI arr=STV fn=SG 3426 dt=20230114.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUQ|SG 2910 |GOI-BLR|GOI      |22:10:00       |22:27:02     |23:24:05      |BLR    |00:00:00       |2595|2700         |1107        |01:50         |01:07         |00:57     |1593       |ALL _1_ ac=VT-SUQ dep=GOI arr=BLR fn=SEJ2910 dt=20230115.csv|2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 1084 |AMD-PNQ|AMD      |19:45:00       |19:55:57     |20:57:40      |PNQ    |21:05:00       |2395|2500         |1118        |01:20         |01:12         |01:01     |1382       |ALL ac=VT-SUG dep=AMD arr=PNQ fn=SEJ1084 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 2975 |AMD-JAI|AMD      |23:25:00       |23:39:02     |00:38:30      |JAI    |00:45:00       |2995|3100         |1052        |01:20         |01:11         |00:59     |2048       |ALL ac=VT-SUG dep=AMD arr=JAI fn=SEJ2975 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 1080 |BHU-PNQ|BHU      |12:50:00       |13:06:03     |13:58:26      |PNQ    |14:05:00       |1995|2100         |948         |01:15         |01:03         |00:52     |1152       |ALL ac=VT-SUG dep=BHU arr=PNQ fn=SEJ1080 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 1082 |BOM-BHU|BOM      |11:20:00       |11:41:52     |12:26:48      |BHU    |12:30:00       |2895|3000         |900         |01:10         |01:07         |00:44     |2100       |ALL ac=VT-SUG dep=BOM arr=BHU fn=SEJ1082 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 2972 |JAI-AMD|JAI      |18:00:00       |18:14:18     |19:20:46      |AMD    |19:25:00       |3145|3250         |1200        |01:25         |01:20         |01:06     |2050       |ALL ac=VT-SUG dep=JAI arr=AMD fn=SEJ2972 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 1078 |PNQ-AMD|PNQ      |21:40:00       |21:55:03     |23:03:58      |AMD    |23:10:00       |3095|3200         |1222        |01:30         |01:20         |01:08     |1978       |ALL ac=VT-SUG dep=PNQ arr=AMD fn=SEJ1078 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUQ|SG 2928 |GWL-BLR|GWL      |10:20:00       |10:30:29     |13:20:08      |BLR    |13:25:00       |4145|4250         |2704        |03:05         |03:03         |02:49     |1546       |ALL _1_ ac=VT-SUQ dep=GWL arr=BLR fn=SEJ2928 dt=20230115.csv|2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 1083 |PNQ-AMD|PNQ      |14:30:00       |15:30:03     |15:43:39      |AMD    |15:50:00       |3095|3200         |1127        |01:20         |01:17         |01:04     |2073       |ALL ac=VT-SUG dep=PNQ arr=AMD fn=SEJ1083 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 1081 |BHU-BOM|BHU      |09:15:00       |09:27:14     |10:10:34      |BOM    |10:25:00       |2495|2600         |839         |01:10         |01:02         |00:43     |1761       |ALL ac=VT-SUG dep=BHU arr=BOM fn=SEJ1081 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUQ|SG 4004 |SAG-BLR|SAG      |16:25:00       |16:34:34     |18:08:25      |BLR    |18:15:00       |3095|3200         |1514        |01:50         |01:47         |01:33     |1686       |ALL ac=VT-SUQ dep=SAG arr=BLR fn=SEJ4004 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUQ|SG 4005 |BLR-SAG|BLR      |13:58:00       |15:30:00     |15:47:12      |SAG    |15:53:00       |4590|4695         |1521        |01:55         |01:52         |01:37     |3174       |ALL ac=VT-SUQ dep=BLR arr=SAG fn=SEJ4005 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-15|VT-SUG|SG 2971 |AMD-JAI|AMD      |16:20:00       |16:31:09     |17:38:20      |JAI    |17:40:00       |2695|2800         |1126        |01:20         |01:17         |01:07     |1674       |ALL ac=VT-SUG dep=AMD arr=JAI fn=SEJ2971 dt=20230115.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
|2023-01-16|VT-SUG|SG 3762 |JAI-AMD|JAI      |05:55:00       |06:30:01     |07:17:01      |AMD    |07:25:00       |null|null         |1224        |01:30         |01:20         |01:06     |null       |ALL ac=VT-SUG dep=JAI arr=AMD fn=SEJ3762 dt=20230116.csv    |2023-01-17 00:41:38.443|2023|January|2023-01-17 09:45:59.551|
+----------+------+--------+-------+---------+---------------+-------------+--------------+-------+---------------+----+-------------+------------+--------------+--------------+----------+-----------+------------------------------------------------------------+-----------------------+----+-------+-----------------------+