In [ ]:
spd_gnd_DF = spark.sql(f'''

        SELECT FileName,
                `Normal-Acceleration`,
                Phase,
                `Time-In-Secs`
        FROM(
                SELECT ROW_NUMBER() OVER(PARTITION BY FileName
                                        ORDER BY CAST(`Time-In-Secs` AS FLOAT) ASC) AS RN,
                        *
                FROM(
                        SELECT FileName,
                                        `Normal-Acceleration`,
                                        Phase,
                                        MIN(CAST(`Time-In-Secs` AS FLOAT)) AS `Time-In-Secs`

                                FROM
                                        (SELECT  *
                                        
                                            FROM 

                                            (
                                                SELECT


                                                        CASE 
                                                            WHEN CAST(`Time-In-Secs` AS FLOAT) < d2.MinTimeSec THEN 'TakeOff'
                                                            WHEN CAST(`Time-In-Secs` AS FLOAT) between d2.MinTimeSec AND d2.MaxTimeSec THEN 'Airborne'
                                                            WHEN CAST(`Time-In-Secs` AS FLOAT)>d2.MaxTimeSec THEN 'Approach' 
                                                        END Phase
                                                        , 
                                                        d2.MaxTimeSec, bo.*

                                                FROM Q400Interim AS bo
                                                JOIN
                                                    (SELECT 
                                                            a.FileName,
                                                            CAST(a.`Radio-Altitude` AS INT) AS MaxRadioHt1,
                                                            MIN(CAST(`Time-In-Secs` AS FLOAT)) AS MinTimeSec,
                                                            MAX(CAST(`Time-In-Secs` AS FLOAT)) AS MaxTimeSec 

                                                    FROM Q400Interim AS a

                                                    JOIN (
                                                            SELECT 
                                                                    FileName,
                                                                    MAX(CAST(`Radio-Altitude` AS INT)) AS MaxRadioHt

                                                            FROM Q400Interim

                                                            GROUP BY FileName) AS d1

                                                    ON a.FileName = d1.FileName

                                                    AND CAST(a.`Radio-Altitude` AS INT) = CAST(d1.MaxRadioHt AS INT)

                                                    GROUP BY a.FileName, a.`Radio-Altitude`
                                                            ) AS d2
                                                ON d2.FileName = bo.FileName 
                                                    ) AS d3

                                            WHERE d3.Phase = 'Approach' ) AS d4

                                        WHERE d4.`Main-WOW` = '{MainWOW}' 
                                        
                                        GROUP BY FileName,
                                                Phase,
                                                `Normal-Acceleration`
                                ) AS d5
                        
                        )
            WHERE RN=1    ''')